// Generated by scripts/generate-aot.py. Do not edit.
#import <NativeScript/NativeScriptAOT.h>
#import <Foundation/Foundation.h>
#import <objc/message.h>
#import <objc/runtime.h>

typedef void (*AOTSendFn)(void);

// x86_64 returns a struct through a hidden pointer, and needs the _stret entry
// points, when it is classified MEMORY. Size over 16 bytes approximates that
// classification; smaller structs with unaligned or long double fields are not
// modeled. arm64 never uses _stret.
#if defined(__x86_64__)
#define AOT_SEND_STRET(T) (sizeof(T) > 16 ? (AOTSendFn)objc_msgSend_stret : (AOTSendFn)objc_msgSend)
#define AOT_SEND_SUPER_STRET(T) \
  (sizeof(T) > 16 ? (AOTSendFn)objc_msgSendSuper_stret : (AOTSendFn)objc_msgSendSuper)
#else
#define AOT_SEND_STRET(T) ((AOTSendFn)objc_msgSend)
#define AOT_SEND_SUPER_STRET(T) ((AOTSendFn)objc_msgSendSuper)
#endif

typedef struct {
  int x;
  int y;
} AOT_TNSSimpleStruct;
typedef struct {
  AOT_TNSSimpleStruct a;
  AOT_TNSSimpleStruct b;
} AOT_TNSNestedStruct;
typedef struct {
  long long x;
  long long y;
  long long z;
} AOT_TNSStruct32;
typedef struct {
  int x1;
  struct { short x2; struct { signed char x3[2]; } y2; } y1[2];
  long long x4;
} AOT_TNSComplexStruct;
typedef struct {
  double x;
  double y;
} AOT_CGPoint;
typedef struct {
  double width;
  double height;
} AOT_CGSize;
typedef struct {
  AOT_CGPoint origin;
  AOT_CGSize size;
} AOT_CGRect;

static bool AOT_TNSBaseInterface_baseMethod(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(baseMethod);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      ((void (*)(struct objc_super*, SEL))objc_msgSendSuper)(&sup, sel);
    } else {
      ((void (*)(id, SEL))objc_msgSend)(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  return true;
}

static bool AOT_TNSBaseInterface_baseMethod_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(baseMethod);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  @try {
    ((void (*)(id, SEL))objc_msgSend)((id)cls, sel);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  return true;
}

static bool AOT_TNSBaseInterface_methodWithParam(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithParam:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  id a0 = nil;
  if (!__ns_aot_arg_object(info, 0, &a0)) return true;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      ((void (*)(struct objc_super*, SEL, id))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      ((void (*)(id, SEL, id))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  return true;
}

static bool AOT_TNSDerivedInterface_methodWith_param(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 2) return false;
  SEL sel = @selector(methodWith:param:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  id a0 = nil;
  if (!__ns_aot_arg_object(info, 0, &a0)) return true;
  id a1 = nil;
  if (!__ns_aot_arg_object(info, 1, &a1)) return true;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      ((void (*)(struct objc_super*, SEL, id, id))objc_msgSendSuper)(&sup, sel, a0, a1);
    } else {
      ((void (*)(id, SEL, id, id))objc_msgSend)(target, sel, a0, a1);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  return true;
}

static bool AOT_TNSBaseInterface_callBaseMethod(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(callBaseMethod:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  BOOL a0 = NO;
  if (!__ns_aot_arg_bool(info, 0, &a0)) return true;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      ((void (*)(struct objc_super*, SEL, BOOL))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      ((void (*)(id, SEL, BOOL))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  return true;
}

static bool AOT_TNSBaseInterface_baseProperty(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(baseProperty);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  int r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((int (*)(struct objc_super*, SEL))objc_msgSendSuper)(&sup, sel);
    } else {
      r = ((int (*)(id, SEL))objc_msgSend)(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_int64(info, (int64_t)r);
  return true;
}

static bool AOT_TNSBaseInterface_setBaseProperty(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(setBaseProperty:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  int64_t raw0 = 0;
  if (!__ns_aot_arg_int64(info, 0, &raw0)) return true;
  int a0 = (int)raw0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      ((void (*)(struct objc_super*, SEL, int))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      ((void (*)(id, SEL, int))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  return true;
}

static bool AOT_TNSBaseInterface_baseProperty_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(baseProperty);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  int r = 0;
  @try {
    r = ((int (*)(id, SEL))objc_msgSend)((id)cls, sel);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_int64(info, (int64_t)r);
  return true;
}

static bool AOT_TNSApi_customGetter(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(customGetter);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  int r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((int (*)(struct objc_super*, SEL))objc_msgSendSuper)(&sup, sel);
    } else {
      r = ((int (*)(id, SEL))objc_msgSend)(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_int64(info, (int64_t)r);
  return true;
}

static bool AOT_TNSApi_methodThrowsException(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(methodThrowsException);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      ((void (*)(struct objc_super*, SEL))objc_msgSendSuper)(&sup, sel);
    } else {
      ((void (*)(id, SEL))objc_msgSend)(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  return true;
}

static bool AOT_TNSSwizzleKlass_instanceMethod(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(instanceMethod:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  int64_t raw0 = 0;
  if (!__ns_aot_arg_int64(info, 0, &raw0)) return true;
  int a0 = (int)raw0;
  int r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((int (*)(struct objc_super*, SEL, int))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((int (*)(id, SEL, int))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_int64(info, (int64_t)r);
  return true;
}

static bool AOT_TNSSwizzleKlass_staticMethod_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(staticMethod:);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  int64_t raw0 = 0;
  if (!__ns_aot_arg_int64(info, 0, &raw0)) return true;
  int a0 = (int)raw0;
  int r = 0;
  @try {
    r = ((int (*)(id, SEL, int))objc_msgSend)((id)cls, sel, a0);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_int64(info, (int64_t)r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithChar(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithChar:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  int64_t raw0 = 0;
  if (!__ns_aot_arg_int64(info, 0, &raw0)) return true;
  signed char a0 = (signed char)raw0;
  signed char r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((signed char (*)(struct objc_super*, SEL, signed char))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((signed char (*)(id, SEL, signed char))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_int64(info, (int64_t)r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithUChar(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithUChar:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  uint64_t raw0 = 0;
  if (!__ns_aot_arg_uint64(info, 0, &raw0)) return true;
  unsigned char a0 = (unsigned char)raw0;
  unsigned char r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((unsigned char (*)(struct objc_super*, SEL, unsigned char))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((unsigned char (*)(id, SEL, unsigned char))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_uint64(info, (uint64_t)r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithInt(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithInt:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  int64_t raw0 = 0;
  if (!__ns_aot_arg_int64(info, 0, &raw0)) return true;
  int a0 = (int)raw0;
  int r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((int (*)(struct objc_super*, SEL, int))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((int (*)(id, SEL, int))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_int64(info, (int64_t)r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithFloat(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithFloat:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  double raw0 = 0;
  if (!__ns_aot_arg_double(info, 0, &raw0)) return true;
  float a0 = (float)raw0;
  float r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((float (*)(struct objc_super*, SEL, float))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((float (*)(id, SEL, float))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_double(info, (double)r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithDouble_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithDouble:);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  double raw0 = 0;
  if (!__ns_aot_arg_double(info, 0, &raw0)) return true;
  double a0 = (double)raw0;
  double r = 0;
  @try {
    r = ((double (*)(id, SEL, double))objc_msgSend)((id)cls, sel, a0);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_double(info, r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithBool2(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithBool2:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  BOOL a0 = NO;
  if (!__ns_aot_arg_bool(info, 0, &a0)) return true;
  BOOL r = NO;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((BOOL (*)(struct objc_super*, SEL, BOOL))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((BOOL (*)(id, SEL, BOOL))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_bool(info, r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithBool3(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithBool3:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  BOOL a0 = NO;
  if (!__ns_aot_arg_bool(info, 0, &a0)) return true;
  BOOL r = NO;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((BOOL (*)(struct objc_super*, SEL, BOOL))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((BOOL (*)(id, SEL, BOOL))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_bool(info, r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithSelector(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithSelector:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  SEL a0 = NULL;
  if (!__ns_aot_arg_selector(info, 0, &a0)) return true;
  SEL r = NULL;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((SEL (*)(struct objc_super*, SEL, SEL))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((SEL (*)(id, SEL, SEL))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_selector(info, r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithClass(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithClass:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  Class a0 = Nil;
  if (!__ns_aot_arg_class(info, 0, &a0)) return true;
  Class r = Nil;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((Class (*)(struct objc_super*, SEL, Class))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((Class (*)(id, SEL, Class))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_class(info, r);
  return true;
}

static bool AOT_TNSPrimitives_methodWithNSNumber(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithNSNumber:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  id a0 = nil;
  if (!__ns_aot_arg_object(info, 0, &a0)) return true;
  id r = nil;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((id (*)(struct objc_super*, SEL, id))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((id (*)(id, SEL, id))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_object(info, r, false, true);
  return true;
}

static bool AOT_TNSPrimitives_methodWithId_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithId:);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  id a0 = nil;
  if (!__ns_aot_arg_object(info, 0, &a0)) return true;
  id r = nil;
  @try {
    r = ((id (*)(id, SEL, id))objc_msgSend)((id)cls, sel, a0);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_object(info, r, false, true);
  return true;
}

static bool AOT_TNSObjCTypes_methodWithNSDate(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(methodWithNSDate:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  id a0 = nil;
  if (!__ns_aot_arg_object(info, 0, &a0)) return true;
  id r = nil;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((id (*)(struct objc_super*, SEL, id))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((id (*)(id, SEL, id))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_object(info, r, false, true);
  return true;
}

static bool AOT_TNSTestNativeCallbacks_recordsSimpleStruct_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  static NSAOTStructType st0 = NULL;
  if (!st0) st0 = __ns_aot_struct_type("TNSSimpleStruct");
  if (!st0) return false;
  SEL sel = @selector(recordsSimpleStruct:);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  AOT_TNSSimpleStruct a0;
  if (!__ns_aot_arg_struct(info, 0, st0, &a0)) return true;
  AOT_TNSSimpleStruct r;
  @try {
    r = ((AOT_TNSSimpleStruct (*)(id, SEL, AOT_TNSSimpleStruct))AOT_SEND_STRET(AOT_TNSSimpleStruct))((id)cls, sel, a0);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_struct(info, st0, &r);
  return true;
}

static bool AOT_TNSTestNativeCallbacks_recordsNestedStruct_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  static NSAOTStructType st0 = NULL;
  if (!st0) st0 = __ns_aot_struct_type("TNSNestedStruct");
  if (!st0) return false;
  SEL sel = @selector(recordsNestedStruct:);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  AOT_TNSNestedStruct a0;
  if (!__ns_aot_arg_struct(info, 0, st0, &a0)) return true;
  AOT_TNSNestedStruct r;
  @try {
    r = ((AOT_TNSNestedStruct (*)(id, SEL, AOT_TNSNestedStruct))AOT_SEND_STRET(AOT_TNSNestedStruct))((id)cls, sel, a0);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_struct(info, st0, &r);
  return true;
}

static bool AOT_TNSTestNativeCallbacks_recordsStruct32_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  static NSAOTStructType st0 = NULL;
  if (!st0) st0 = __ns_aot_struct_type("TNSStruct32");
  if (!st0) return false;
  SEL sel = @selector(recordsStruct32:);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  AOT_TNSStruct32 a0;
  if (!__ns_aot_arg_struct(info, 0, st0, &a0)) return true;
  AOT_TNSStruct32 r;
  @try {
    r = ((AOT_TNSStruct32 (*)(id, SEL, AOT_TNSStruct32))AOT_SEND_STRET(AOT_TNSStruct32))((id)cls, sel, a0);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_struct(info, st0, &r);
  return true;
}

static bool AOT_TNSTestNativeCallbacks_recordsComplexStruct_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  static NSAOTStructType st0 = NULL;
  if (!st0) st0 = __ns_aot_struct_type("TNSComplexStruct");
  if (!st0) return false;
  SEL sel = @selector(recordsComplexStruct:);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  AOT_TNSComplexStruct a0;
  if (!__ns_aot_arg_struct(info, 0, st0, &a0)) return true;
  AOT_TNSComplexStruct r;
  @try {
    r = ((AOT_TNSComplexStruct (*)(id, SEL, AOT_TNSComplexStruct))AOT_SEND_STRET(AOT_TNSComplexStruct))((id)cls, sel, a0);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_struct(info, st0, &r);
  return true;
}

static bool AOT_RectClass_getRect(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  static NSAOTStructType st0 = NULL;
  if (!st0) st0 = __ns_aot_struct_type("CGRect");
  if (!st0) return false;
  SEL sel = @selector(getRect);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  AOT_CGRect r;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((AOT_CGRect (*)(struct objc_super*, SEL))AOT_SEND_SUPER_STRET(AOT_CGRect))(&sup, sel);
    } else {
      r = ((AOT_CGRect (*)(id, SEL))AOT_SEND_STRET(AOT_CGRect))(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_struct(info, st0, &r);
  return true;
}

static bool AOT_UIScreen_mainScreen_static(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(mainScreen);
  Class cls = __ns_aot_get_static_class(info);
  if (cls == nil) return false;
  id r = nil;
  @try {
    r = ((id (*)(id, SEL))objc_msgSend)((id)cls, sel);
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_object(info, r, false, true);
  return true;
}

static bool AOT_UIScreen_scale(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(scale);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  double r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((double (*)(struct objc_super*, SEL))objc_msgSendSuper)(&sup, sel);
    } else {
      r = ((double (*)(id, SEL))objc_msgSend)(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_double(info, r);
  return true;
}

static bool AOT_UIScreen_nativeScale(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(nativeScale);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  double r = 0;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((double (*)(struct objc_super*, SEL))objc_msgSendSuper)(&sup, sel);
    } else {
      r = ((double (*)(id, SEL))objc_msgSend)(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_double(info, r);
  return true;
}

static bool AOT_UIScreen_bounds(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  static NSAOTStructType st0 = NULL;
  if (!st0) st0 = __ns_aot_struct_type("CGRect");
  if (!st0) return false;
  SEL sel = @selector(bounds);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  AOT_CGRect r;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((AOT_CGRect (*)(struct objc_super*, SEL))AOT_SEND_SUPER_STRET(AOT_CGRect))(&sup, sel);
    } else {
      r = ((AOT_CGRect (*)(id, SEL))AOT_SEND_STRET(AOT_CGRect))(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_struct(info, st0, &r);
  return true;
}

static bool AOT_NSObject_description(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 0) return false;
  SEL sel = @selector(description);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  id r = nil;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((id (*)(struct objc_super*, SEL))objc_msgSendSuper)(&sup, sel);
    } else {
      r = ((id (*)(id, SEL))objc_msgSend)(target, sel);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_object(info, r, false, true);
  return true;
}

static bool AOT_NSObject_respondsToSelector(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(respondsToSelector:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  SEL a0 = NULL;
  if (!__ns_aot_arg_selector(info, 0, &a0)) return true;
  BOOL r = NO;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((BOOL (*)(struct objc_super*, SEL, SEL))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((BOOL (*)(id, SEL, SEL))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_bool(info, r);
  return true;
}

static bool AOT_NSObject_isKindOfClass(NSAOTCallInfo info) {
  if (__ns_aot_arg_count(info) != 1) return false;
  SEL sel = @selector(isKindOfClass:);
  bool callSuper = false;
  id target = __ns_aot_get_target(info, sel, &sel, &callSuper);
  if (target == nil) return false;
  Class a0 = Nil;
  if (!__ns_aot_arg_class(info, 0, &a0)) return true;
  BOOL r = NO;
  @try {
    if (callSuper) {
      struct objc_super sup = {target, class_getSuperclass(object_getClass(target))};
      r = ((BOOL (*)(struct objc_super*, SEL, Class))objc_msgSendSuper)(&sup, sel, a0);
    } else {
      r = ((BOOL (*)(id, SEL, Class))objc_msgSend)(target, sel, a0);
    }
  } @catch (NSException* e) {
    __ns_aot_throw_exception(info, e);
    return true;
  }
  __ns_aot_return_bool(info, r);
  return true;
}

__attribute__((visibility("default")))
void __ns_register_aot_calls(void (*reg)(const char*, const char*, bool, NSAOTCallHandler)) {
  reg("TNSBaseInterface", "baseMethod", false, AOT_TNSBaseInterface_baseMethod);
  reg("TNSBaseInterface", "baseMethod", true, AOT_TNSBaseInterface_baseMethod_static);
  reg("TNSBaseInterface", "methodWithParam:", false, AOT_TNSBaseInterface_methodWithParam);
  reg("TNSDerivedInterface", "methodWithParam:", false, AOT_TNSBaseInterface_methodWithParam);
  reg("TNSDerivedInterface", "methodWith:param:", false, AOT_TNSDerivedInterface_methodWith_param);
  reg("TNSBaseInterface", "callBaseMethod:", false, AOT_TNSBaseInterface_callBaseMethod);
  reg("TNSBaseInterface", "baseProperty", false, AOT_TNSBaseInterface_baseProperty);
  reg("TNSBaseInterface", "setBaseProperty:", false, AOT_TNSBaseInterface_setBaseProperty);
  reg("TNSBaseInterface", "baseProperty", true, AOT_TNSBaseInterface_baseProperty_static);
  reg("TNSApi", "customGetter", false, AOT_TNSApi_customGetter);
  reg("TNSApi", "methodThrowsException", false, AOT_TNSApi_methodThrowsException);
  reg("TNSSwizzleKlass", "instanceMethod:", false, AOT_TNSSwizzleKlass_instanceMethod);
  reg("TNSSwizzleKlass", "staticMethod:", true, AOT_TNSSwizzleKlass_staticMethod_static);
  reg("TNSPrimitives", "methodWithChar:", false, AOT_TNSPrimitives_methodWithChar);
  reg("TNSPrimitives", "methodWithUChar:", false, AOT_TNSPrimitives_methodWithUChar);
  reg("TNSPrimitives", "methodWithInt:", false, AOT_TNSPrimitives_methodWithInt);
  reg("TNSPrimitives", "methodWithFloat:", false, AOT_TNSPrimitives_methodWithFloat);
  reg("TNSPrimitives", "methodWithDouble:", true, AOT_TNSPrimitives_methodWithDouble_static);
  reg("TNSPrimitives", "methodWithBool2:", false, AOT_TNSPrimitives_methodWithBool2);
  reg("TNSPrimitives", "methodWithBool3:", false, AOT_TNSPrimitives_methodWithBool3);
  reg("TNSPrimitives", "methodWithSelector:", false, AOT_TNSPrimitives_methodWithSelector);
  reg("TNSPrimitives", "methodWithClass:", false, AOT_TNSPrimitives_methodWithClass);
  reg("TNSPrimitives", "methodWithNSNumber:", false, AOT_TNSPrimitives_methodWithNSNumber);
  reg("TNSPrimitives", "methodWithId:", true, AOT_TNSPrimitives_methodWithId_static);
  reg("TNSObjCTypes", "methodWithNSDate:", false, AOT_TNSObjCTypes_methodWithNSDate);
  reg("TNSTestNativeCallbacks", "recordsSimpleStruct:", true, AOT_TNSTestNativeCallbacks_recordsSimpleStruct_static);
  reg("TNSTestNativeCallbacks", "recordsNestedStruct:", true, AOT_TNSTestNativeCallbacks_recordsNestedStruct_static);
  reg("TNSTestNativeCallbacks", "recordsStruct32:", true, AOT_TNSTestNativeCallbacks_recordsStruct32_static);
  reg("TNSTestNativeCallbacks", "recordsComplexStruct:", true, AOT_TNSTestNativeCallbacks_recordsComplexStruct_static);
  reg("RectClass", "getRect", false, AOT_RectClass_getRect);
  reg("UIScreen", "mainScreen", true, AOT_UIScreen_mainScreen_static);
  reg("UIScreen", "scale", false, AOT_UIScreen_scale);
  reg("UIScreen", "nativeScale", false, AOT_UIScreen_nativeScale);
  reg("UIScreen", "bounds", false, AOT_UIScreen_bounds);
  reg("NSObject", "description", false, AOT_NSObject_description);
  reg("NSObject", "respondsToSelector:", false, AOT_NSObject_respondsToSelector);
  reg("NSObject", "isKindOfClass:", false, AOT_NSObject_isKindOfClass);
}
