// AUTO-GENERATED by scripts/generate-aot.py — do not edit manually.
#include "AOTDirectCalls.h"
#include <Foundation/Foundation.h>
#include <objc/message.h>
#include "ArgConverter.h"
#include "Caches.h"
#include "Helpers.h"
#include "Interop.h"
#include "NativeScriptException.h"

using namespace v8;

namespace tns {

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static inline id AOTExtractTarget(Isolate* isolate, Local<Object> receiver, bool& callSuper) {
  BaseDataWrapper* wrapper = tns::GetValue(isolate, receiver);
  if (wrapper == nullptr) {
    callSuper = false;
    return nil;
  }

  id target = nil;
  callSuper = false;

  if (wrapper->Type() == WrapperType::ObjCAllocObject) {
    ObjCAllocDataWrapper* allocWrapper = static_cast<ObjCAllocDataWrapper*>(wrapper);
    target = [allocWrapper->Klass() alloc];
  } else if (wrapper->Type() == WrapperType::ObjCObject) {
    ObjCDataWrapper* objcWrapper = static_cast<ObjCDataWrapper*>(wrapper);
    target = objcWrapper->Data();
    std::string className = object_getClassName(target);
    auto cache = Caches::Get(isolate);
    callSuper = cache->ClassPrototypes.find(className) != cache->ClassPrototypes.end();
  }

  return target;
}

__unused static inline Local<Value> AOTWrapId(Local<Context> context, id result) {
  Isolate* isolate = context->GetIsolate();
  if (result == nil) return Null(isolate);

  if ([result isKindOfClass:[NSNull class]]) {
    return Null(isolate);
  }
  if ([result isKindOfClass:[NSString class]] && ![result isKindOfClass:[NSMutableString class]]) {
    return tns::ToV8String(isolate, (NSString*)result);
  }
  if ([result isKindOfClass:[NSNumber class]] && ![result isKindOfClass:[NSDecimalNumber class]]) {
    return Number::New(isolate, [(NSNumber*)result doubleValue]);
  }

  auto* wrapper = new ObjCDataWrapper(result);
  Local<Value> jsResult = ArgConverter::ConvertArgument(context, wrapper);
  tns::DeleteWrapperIfUnused(isolate, jsResult, wrapper);
  return jsResult;
}

__unused static inline id AOTToObject(Local<Context> context, Local<Value> arg) {
  Isolate* isolate = context->GetIsolate();
  if (!arg.IsEmpty() && arg->IsObject()) {
    BaseDataWrapper* wrapper = tns::GetValue(isolate, arg);
    if (wrapper) {
      switch (wrapper->Type()) {
        case WrapperType::ObjCObject:
        case WrapperType::ObjCClass:
        case WrapperType::ObjCProtocol:
          break;
        case WrapperType::ObjCAllocObject:
          return [static_cast<ObjCAllocDataWrapper*>(wrapper)->Klass() alloc];
        case WrapperType::Pointer:
          return (id) static_cast<PointerWrapper*>(wrapper)->Data();
        default:
          return nil;
      }
    }
  }
  return Interop::ToObject(context, arg);
}

__unused static inline Local<Value> AOTWrapString(Local<Context> context, id result) {
  Isolate* isolate = context->GetIsolate();
  if (result == nil) return Null(isolate);
  return tns::ToV8String(isolate, (NSString*)result);
}

__unused static inline Local<Value> AOTWrapObject(Local<Context> context, id result) {
  Isolate* isolate = context->GetIsolate();
  if (result == nil) return Null(isolate);

  auto* wrapper = new ObjCDataWrapper(result);
  Local<Value> jsResult = ArgConverter::ConvertArgument(context, wrapper);
  tns::DeleteWrapperIfUnused(isolate, jsResult, wrapper);
  return jsResult;
}

// ---------------------------------------------------------------------------
// Per-method stubs (18 methods)
// ---------------------------------------------------------------------------

// NSObject -[respondsToSelector:]
static void AOT_NSObject_respondsToSelector(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  SEL arg0 = sel_registerName(tns::ToString(isolate, info[0]).c_str());

  BOOL result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((BOOL (*)(objc_super*, SEL, SEL))objc_msgSendSuper)(
        &sup, @selector(respondsToSelector:), arg0);
  } else {
    result = [(NSObject*)target respondsToSelector:arg0];
  }

  info.GetReturnValue().Set(v8::Boolean::New(isolate, result));
}

// NSObject -[isKindOfClass:]
static void AOT_NSObject_isKindOfClass(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  Class arg0 = nil;
  BaseDataWrapper* argW0 = tns::GetValue(isolate, info[0]);
  if (argW0 != nullptr && argW0->Type() == WrapperType::ObjCClass)
    arg0 = static_cast<ObjCClassWrapper*>(argW0)->Klass();
  else if (tns::IsString(info[0]))
    arg0 = objc_getClass(tns::ToString(isolate, info[0]).c_str());

  BOOL result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((BOOL (*)(objc_super*, SEL, Class))objc_msgSendSuper)(&sup, @selector(isKindOfClass:),
                                                                    arg0);
  } else {
    result = [(NSObject*)target isKindOfClass:arg0];
  }

  info.GetReturnValue().Set(v8::Boolean::New(isolate, result));
}

// NSObject -[isEqual:]
static void AOT_NSObject_isEqual(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  id arg0 = AOTToObject(context, info[0]);

  BOOL result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((BOOL (*)(objc_super*, SEL, id))objc_msgSendSuper)(&sup, @selector(isEqual:), arg0);
  } else {
    result = [(NSObject*)target isEqual:arg0];
  }

  info.GetReturnValue().Set(v8::Boolean::New(isolate, result));
}

// NSObject -[description]
static void AOT_NSObject_description(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;

  id result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((id (*)(objc_super*, SEL))objc_msgSendSuper)(&sup, @selector(description));
  } else {
    result = [(NSObject*)target description];
  }

  info.GetReturnValue().Set(AOTWrapId(context, result));
}

// NSObject -[hash]
static void AOT_NSObject_hash(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;

  unsigned long result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((unsigned long (*)(objc_super*, SEL))objc_msgSendSuper)(&sup, @selector(hash));
  } else {
    result = [(NSObject*)target hash];
  }

  info.GetReturnValue().Set(Number::New(isolate, (double)result));
}

// NSMutableArray -[removeAllObjects]
static void AOT_NSMutableArray_removeAllObjects(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;

  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    ((void (*)(objc_super*, SEL))objc_msgSendSuper)(&sup, @selector(removeAllObjects));
  } else {
    [(NSMutableArray*)target removeAllObjects];
  }
}

// NSMutableArray -[addObject:]
static void AOT_NSMutableArray_addObject(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  id arg0 = AOTToObject(context, info[0]);

  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    ((void (*)(objc_super*, SEL, id))objc_msgSendSuper)(&sup, @selector(addObject:), arg0);
  } else {
    [(NSMutableArray*)target addObject:arg0];
  }
}

// NSMutableArray -[objectAtIndex:]
static void AOT_NSMutableArray_objectAtIndex(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  unsigned long arg0 = (unsigned long)tns::ToNumber(isolate, info[0]);

  id result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((id (*)(objc_super*, SEL, unsigned long))objc_msgSendSuper)(
        &sup, @selector(objectAtIndex:), arg0);
  } else {
    result = [(NSMutableArray*)target objectAtIndex:arg0];
  }

  info.GetReturnValue().Set(AOTWrapId(context, result));
}

// NSMutableArray -[count]
static void AOT_NSMutableArray_count(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;

  unsigned long result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((unsigned long (*)(objc_super*, SEL))objc_msgSendSuper)(&sup, @selector(count));
  } else {
    result = [(NSMutableArray*)target count];
  }

  info.GetReturnValue().Set(Number::New(isolate, (double)result));
}

// NSMutableArray -[insertObject:atIndex:]
static void AOT_NSMutableArray_insertObject_atIndex(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  id arg0 = AOTToObject(context, info[0]);
  unsigned long arg1 = (unsigned long)tns::ToNumber(isolate, info[1]);

  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    ((void (*)(objc_super*, SEL, id, unsigned long))objc_msgSendSuper)(
        &sup, @selector(insertObject:atIndex:), arg0, arg1);
  } else {
    [(NSMutableArray*)target insertObject:arg0 atIndex:arg1];
  }
}

// NSMutableArray -[removeObjectAtIndex:]
static void AOT_NSMutableArray_removeObjectAtIndex(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  unsigned long arg0 = (unsigned long)tns::ToNumber(isolate, info[0]);

  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    ((void (*)(objc_super*, SEL, unsigned long))objc_msgSendSuper)(
        &sup, @selector(removeObjectAtIndex:), arg0);
  } else {
    [(NSMutableArray*)target removeObjectAtIndex:arg0];
  }
}

// NSArray -[objectAtIndex:]
static void AOT_NSArray_objectAtIndex(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  unsigned long arg0 = (unsigned long)tns::ToNumber(isolate, info[0]);

  id result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((id (*)(objc_super*, SEL, unsigned long))objc_msgSendSuper)(
        &sup, @selector(objectAtIndex:), arg0);
  } else {
    result = [(NSArray*)target objectAtIndex:arg0];
  }

  info.GetReturnValue().Set(AOTWrapId(context, result));
}

// NSArray -[count]
static void AOT_NSArray_count(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;

  unsigned long result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((unsigned long (*)(objc_super*, SEL))objc_msgSendSuper)(&sup, @selector(count));
  } else {
    result = [(NSArray*)target count];
  }

  info.GetReturnValue().Set(Number::New(isolate, (double)result));
}

// NSDictionary -[objectForKeyedSubscript:]
static void AOT_NSDictionary_objectForKeyedSubscript(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  id arg0 = AOTToObject(context, info[0]);

  id result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((id (*)(objc_super*, SEL, id))objc_msgSendSuper)(
        &sup, @selector(objectForKeyedSubscript:), arg0);
  } else {
    result = [(NSDictionary*)target objectForKeyedSubscript:arg0];
  }

  info.GetReturnValue().Set(AOTWrapId(context, result));
}

// NSDictionary -[count]
static void AOT_NSDictionary_count(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;

  unsigned long result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((unsigned long (*)(objc_super*, SEL))objc_msgSendSuper)(&sup, @selector(count));
  } else {
    result = [(NSDictionary*)target count];
  }

  info.GetReturnValue().Set(Number::New(isolate, (double)result));
}

// NSMutableDictionary -[setObject:forKey:]
static void AOT_NSMutableDictionary_setObject_forKey(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  id arg0 = AOTToObject(context, info[0]);
  id arg1 = AOTToObject(context, info[1]);

  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    ((void (*)(objc_super*, SEL, id, id))objc_msgSendSuper)(&sup, @selector(setObject:forKey:),
                                                            arg0, arg1);
  } else {
    [(NSMutableDictionary*)target setObject:arg0 forKey:arg1];
  }
}

// NSMutableDictionary -[removeObjectForKey:]
static void AOT_NSMutableDictionary_removeObjectForKey(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;
  id arg0 = AOTToObject(context, info[0]);

  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    ((void (*)(objc_super*, SEL, id))objc_msgSendSuper)(&sup, @selector(removeObjectForKey:), arg0);
  } else {
    [(NSMutableDictionary*)target removeObjectForKey:arg0];
  }
}

// NSString -[length]
static void AOT_NSString_length(const FunctionCallbackInfo<Value>& info) {
  Isolate* isolate = info.GetIsolate();
  bool callSuper;
  id target = AOTExtractTarget(isolate, info.This(), callSuper);
  if (target == nil) return;

  unsigned long result;
  if (callSuper) {
    objc_super sup = {target, class_getSuperclass(object_getClass(target))};
    result = ((unsigned long (*)(objc_super*, SEL))objc_msgSendSuper)(&sup, @selector(length));
  } else {
    result = [(NSString*)target length];
  }

  info.GetReturnValue().Set(Number::New(isolate, (double)result));
}

// ---------------------------------------------------------------------------
// Block invoke stubs (11 patterns)
// ---------------------------------------------------------------------------

static void AOTBlockInvoke_void_noargs(void* _block) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 0, nullptr).ToLocal(&result);
  (void)success;
}

static void AOTBlockInvoke_void_id(void* _block, id nativeArg0) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<Value> jsArgs[1];
  if (nativeArg0 == nil) {
    jsArgs[0] = Null(isolate);
  } else {
    ObjCDataWrapper* w0 = new ObjCDataWrapper(nativeArg0);
    jsArgs[0] = ArgConverter::ConvertArgument(context, w0);
    tns::DeleteWrapperIfUnused(isolate, jsArgs[0], w0);
  }

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 1, jsArgs).ToLocal(&result);
  (void)success;
}

static void AOTBlockInvoke_void_id_id(void* _block, id nativeArg0, id nativeArg1) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<Value> jsArgs[2];
  if (nativeArg0 == nil) {
    jsArgs[0] = Null(isolate);
  } else {
    ObjCDataWrapper* w0 = new ObjCDataWrapper(nativeArg0);
    jsArgs[0] = ArgConverter::ConvertArgument(context, w0);
    tns::DeleteWrapperIfUnused(isolate, jsArgs[0], w0);
  }
  if (nativeArg1 == nil) {
    jsArgs[1] = Null(isolate);
  } else {
    ObjCDataWrapper* w1 = new ObjCDataWrapper(nativeArg1);
    jsArgs[1] = ArgConverter::ConvertArgument(context, w1);
    tns::DeleteWrapperIfUnused(isolate, jsArgs[1], w1);
  }

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 2, jsArgs).ToLocal(&result);
  (void)success;
}

static void AOTBlockInvoke_void_BOOL(void* _block, BOOL nativeArg0) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<Value> jsArgs[1];
  jsArgs[0] = v8::Boolean::New(isolate, nativeArg0);

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 1, jsArgs).ToLocal(&result);
  (void)success;
}

static void AOTBlockInvoke_void_long(void* _block, long nativeArg0) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<Value> jsArgs[1];
  jsArgs[0] = Number::New(isolate, (double)nativeArg0);

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 1, jsArgs).ToLocal(&result);
  (void)success;
}

static void AOTBlockInvoke_void_ulong(void* _block, unsigned long nativeArg0) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<Value> jsArgs[1];
  jsArgs[0] = Number::New(isolate, (double)nativeArg0);

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 1, jsArgs).ToLocal(&result);
  (void)success;
}

static BOOL AOTBlockInvoke_BOOL_noargs(void* _block) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return (BOOL)0;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 0, nullptr).ToLocal(&result);

  if (!success || result.IsEmpty() || result->IsNullOrUndefined()) {
    return (BOOL)0;
  }
  return tns::ToBool(result);
}

static BOOL AOTBlockInvoke_BOOL_id(void* _block, id nativeArg0) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return (BOOL)0;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<Value> jsArgs[1];
  if (nativeArg0 == nil) {
    jsArgs[0] = Null(isolate);
  } else {
    ObjCDataWrapper* w0 = new ObjCDataWrapper(nativeArg0);
    jsArgs[0] = ArgConverter::ConvertArgument(context, w0);
    tns::DeleteWrapperIfUnused(isolate, jsArgs[0], w0);
  }

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 1, jsArgs).ToLocal(&result);

  if (!success || result.IsEmpty() || result->IsNullOrUndefined()) {
    return (BOOL)0;
  }
  return tns::ToBool(result);
}

static BOOL AOTBlockInvoke_BOOL_id_ulong_BOOL(void* _block, id nativeArg0, unsigned long nativeArg1,
                                              BOOL nativeArg2) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return (BOOL)0;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<Value> jsArgs[3];
  if (nativeArg0 == nil) {
    jsArgs[0] = Null(isolate);
  } else {
    ObjCDataWrapper* w0 = new ObjCDataWrapper(nativeArg0);
    jsArgs[0] = ArgConverter::ConvertArgument(context, w0);
    tns::DeleteWrapperIfUnused(isolate, jsArgs[0], w0);
  }
  jsArgs[1] = Number::New(isolate, (double)nativeArg1);
  jsArgs[2] = v8::Boolean::New(isolate, nativeArg2);

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 3, jsArgs).ToLocal(&result);

  if (!success || result.IsEmpty() || result->IsNullOrUndefined()) {
    return (BOOL)0;
  }
  return tns::ToBool(result);
}

static id AOTBlockInvoke_id_noargs(void* _block) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return nil;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 0, nullptr).ToLocal(&result);

  if (!success || result.IsEmpty() || result->IsNullOrUndefined()) {
    return nil;
  }
  return Interop::ToObject(context, result);
}

static id AOTBlockInvoke_id_id(void* _block, id nativeArg0) {
  Interop::JSBlock* block = static_cast<Interop::JSBlock*>(_block);
  MethodCallbackWrapper* wrapper = static_cast<MethodCallbackWrapper*>(block->userData);
  Isolate* isolate = wrapper->isolateWrapper_.Isolate();

  if (!wrapper->isolateWrapper_.IsValid()) {
    return nil;
  }

  v8::Locker locker(isolate);
  Isolate::Scope isolateScope(isolate);
  HandleScope handleScope(isolate);
  auto cache = Caches::Get(isolate);
  Local<Context> context = cache->GetContext();
  Context::Scope contextScope(context);

  Local<Value> jsArgs[1];
  if (nativeArg0 == nil) {
    jsArgs[0] = Null(isolate);
  } else {
    ObjCDataWrapper* w0 = new ObjCDataWrapper(nativeArg0);
    jsArgs[0] = ArgConverter::ConvertArgument(context, w0);
    tns::DeleteWrapperIfUnused(isolate, jsArgs[0], w0);
  }

  Local<v8::Function> callback = wrapper->callback_->Get(isolate).As<v8::Function>();
  Local<Value> result;
  bool success = callback->Call(context, context->Global(), 1, jsArgs).ToLocal(&result);

  if (!success || result.IsEmpty() || result->IsNullOrUndefined()) {
    return nil;
  }
  return Interop::ToObject(context, result);
}

// ---------------------------------------------------------------------------
// Matchers
// ---------------------------------------------------------------------------

v8::FunctionCallback GetAOTDirectCall(const char* className, const char* selectorName) {
  if (strcmp(className, "NSArray") == 0) {
    if (strcmp(selectorName, "objectAtIndex:") == 0) return AOT_NSArray_objectAtIndex;
    if (strcmp(selectorName, "count") == 0) return AOT_NSArray_count;
  }
  if (strcmp(className, "NSDictionary") == 0) {
    if (strcmp(selectorName, "objectForKeyedSubscript:") == 0)
      return AOT_NSDictionary_objectForKeyedSubscript;
    if (strcmp(selectorName, "count") == 0) return AOT_NSDictionary_count;
  }
  if (strcmp(className, "NSMutableArray") == 0) {
    if (strcmp(selectorName, "removeAllObjects") == 0) return AOT_NSMutableArray_removeAllObjects;
    if (strcmp(selectorName, "addObject:") == 0) return AOT_NSMutableArray_addObject;
    if (strcmp(selectorName, "objectAtIndex:") == 0) return AOT_NSMutableArray_objectAtIndex;
    if (strcmp(selectorName, "count") == 0) return AOT_NSMutableArray_count;
    if (strcmp(selectorName, "insertObject:atIndex:") == 0)
      return AOT_NSMutableArray_insertObject_atIndex;
    if (strcmp(selectorName, "removeObjectAtIndex:") == 0)
      return AOT_NSMutableArray_removeObjectAtIndex;
  }
  if (strcmp(className, "NSMutableDictionary") == 0) {
    if (strcmp(selectorName, "setObject:forKey:") == 0)
      return AOT_NSMutableDictionary_setObject_forKey;
    if (strcmp(selectorName, "removeObjectForKey:") == 0)
      return AOT_NSMutableDictionary_removeObjectForKey;
  }
  if (strcmp(className, "NSObject") == 0) {
    if (strcmp(selectorName, "respondsToSelector:") == 0) return AOT_NSObject_respondsToSelector;
    if (strcmp(selectorName, "isKindOfClass:") == 0) return AOT_NSObject_isKindOfClass;
    if (strcmp(selectorName, "isEqual:") == 0) return AOT_NSObject_isEqual;
    if (strcmp(selectorName, "description") == 0) return AOT_NSObject_description;
    if (strcmp(selectorName, "hash") == 0) return AOT_NSObject_hash;
  }
  if (strcmp(className, "NSString") == 0) {
    if (strcmp(selectorName, "length") == 0) return AOT_NSString_length;
  }
  return nullptr;
}

typedef void* AOTBlockInvokeFunc;

AOTBlockInvokeFunc GetAOTBlockInvoke(const TypeEncoding* typeEncoding, int argsCount) {
  BinaryTypeEncodingType retType = typeEncoding->type;

  if (argsCount == 0) {
    if (retType == BinaryTypeEncodingType::VoidEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_void_noargs;
    if (retType == BinaryTypeEncodingType::BoolEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_BOOL_noargs;
    if (retType == BinaryTypeEncodingType::IdEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_id_noargs;
    return nullptr;
  }

  if (argsCount == 1) {
    const TypeEncoding* pEnc = typeEncoding;
    pEnc = pEnc->next();
    BinaryTypeEncodingType p0Type = pEnc->type;
    if (retType == BinaryTypeEncodingType::VoidEncoding &&
        p0Type == BinaryTypeEncodingType::IdEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_void_id;
    if (retType == BinaryTypeEncodingType::VoidEncoding &&
        p0Type == BinaryTypeEncodingType::BoolEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_void_BOOL;
    if (retType == BinaryTypeEncodingType::VoidEncoding &&
        p0Type == BinaryTypeEncodingType::LongEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_void_long;
    if (retType == BinaryTypeEncodingType::VoidEncoding &&
        p0Type == BinaryTypeEncodingType::ULongEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_void_ulong;
    if (retType == BinaryTypeEncodingType::BoolEncoding &&
        p0Type == BinaryTypeEncodingType::IdEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_BOOL_id;
    if (retType == BinaryTypeEncodingType::IdEncoding &&
        p0Type == BinaryTypeEncodingType::IdEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_id_id;
    return nullptr;
  }

  if (argsCount == 2) {
    const TypeEncoding* pEnc = typeEncoding;
    pEnc = pEnc->next();
    BinaryTypeEncodingType p0Type = pEnc->type;
    pEnc = pEnc->next();
    BinaryTypeEncodingType p1Type = pEnc->type;
    if (retType == BinaryTypeEncodingType::VoidEncoding &&
        p0Type == BinaryTypeEncodingType::IdEncoding &&
        p1Type == BinaryTypeEncodingType::IdEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_void_id_id;
    return nullptr;
  }

  if (argsCount == 3) {
    const TypeEncoding* pEnc = typeEncoding;
    pEnc = pEnc->next();
    BinaryTypeEncodingType p0Type = pEnc->type;
    pEnc = pEnc->next();
    BinaryTypeEncodingType p1Type = pEnc->type;
    pEnc = pEnc->next();
    BinaryTypeEncodingType p2Type = pEnc->type;
    if (retType == BinaryTypeEncodingType::BoolEncoding &&
        p0Type == BinaryTypeEncodingType::IdEncoding &&
        p1Type == BinaryTypeEncodingType::ULongEncoding &&
        p2Type == BinaryTypeEncodingType::BoolEncoding)
      return (AOTBlockInvokeFunc)AOTBlockInvoke_BOOL_id_ulong_BOOL;
    return nullptr;
  }

  return nullptr;
}

}  // namespace tns
