// AUTO-GENERATED by scripts/generate-aot.py — do not edit manually.
#ifndef AOTDirectCalls_h
#define AOTDirectCalls_h

#include "Common.h"
#include "Metadata.h"

namespace tns {

v8::FunctionCallback GetAOTDirectCall(const char* className,
                                      const char* selectorName);

v8::FunctionCallback GetExternalAOTCall(const char* className,
                                        const char* selectorName, bool isStatic,
                                        void** outHandler);
void DiscoverExternalAOTStubs();

typedef void* AOTBlockInvokeFunc;
AOTBlockInvokeFunc GetAOTBlockInvoke(const TypeEncoding* typeEncoding,
                                     int argsCount);

}  // namespace tns

#endif /* AOTDirectCalls_h */
